
'use server';
/**
 * @fileOverview A Genkit flow to handle chat interactions.
 * This flow can interact either with the globally configured LLM or with a specific AI agent
 * by using its system prompt. It's designed for direct chat functionalities within the application.
 *
 * Exports:
 * - `chatWithAgentOrGlobal`: The main function to invoke the flow.
 * - `ChatWithAgentOrGlobalInput`: The Zod schema type for the input.
 * - `ChatWithAgentOrGlobalOutput`: The Zod schema type for the output.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Zod schema for the input to the `chatWithAgentOrGlobalFlow`.
 */
const ChatWithAgentOrGlobalInputSchema = z.object({
  /** The message sent by the user. */
  userMessage: z.string().describe('The message from the user.'),
  /**
   * Optional system prompt of a specific AI agent.
   * If provided, the chat interaction will be contextualized by this agent's persona and instructions.
   * If not provided, a default assistant persona is used.
   */
  agentSystemPrompt: z.string().optional().describe('The system prompt of the specific agent, if one is selected.'),
});
/**
 * TypeScript type inferred from `ChatWithAgentOrGlobalInputSchema`.
 * Represents the input structure for the chat flow.
 */
export type ChatWithAgentOrGlobalInput = z.infer<typeof ChatWithAgentOrGlobalInputSchema>;

/**
 * Zod schema for the output of the `chatWithAgentOrGlobalFlow`.
 */
const ChatWithAgentOrGlobalOutputSchema = z.object({
  /** The response generated by the AI assistant. */
  aiResponse: z.string().describe('The response from the AI assistant.'),
});
/**
 * TypeScript type inferred from `ChatWithAgentOrGlobalOutputSchema`.
 * Represents the output structure from the chat flow.
 */
export type ChatWithAgentOrGlobalOutput = z.infer<typeof ChatWithAgentOrGlobalOutputSchema>;

/**
 * Invokes the chat Genkit flow.
 * This function serves as a wrapper around the Genkit flow, providing a clean interface
 * for use in server-side components or other server actions.
 *
 * @param {ChatWithAgentOrGlobalInput} input - The input containing the user's message and optionally an agent's system prompt.
 * @returns {Promise<ChatWithAgentOrGlobalOutput>} A promise that resolves to the AI's response.
 * @throws {Error} If the LLM fails to generate an output.
 */
export async function chatWithAgentOrGlobal(
  input: ChatWithAgentOrGlobalInput
): Promise<ChatWithAgentOrGlobalOutput> {
  return chatWithAgentOrGlobalFlow(input);
}

/**
 * Genkit prompt definition for the chat interaction.
 * It dynamically adjusts the system message based on whether an `agentSystemPrompt` is provided.
 */
const chatPrompt = ai.definePrompt({
  name: 'chatWithAgentOrGlobalPrompt',
  input: {schema: ChatWithAgentOrGlobalInputSchema},
  output: {schema: ChatWithAgentOrGlobalOutputSchema},
  prompt: `{{#if agentSystemPrompt}}
{{{agentSystemPrompt}}}
{{else}}
Eres un asistente IA general de CodeAlchemist. Eres útil y respondes en castellano.
{{/if}}

Usuario: {{{userMessage}}}
Asistente:`,
});

/**
 * Genkit flow definition for handling chat interactions.
 * This flow takes the user's message and an optional agent system prompt,
 * passes them to the `chatPrompt`, and returns the AI's generated response.
 */
const chatWithAgentOrGlobalFlow = ai.defineFlow(
  {
    name: 'chatWithAgentOrGlobalFlow',
    inputSchema: ChatWithAgentOrGlobalInputSchema,
    outputSchema: ChatWithAgentOrGlobalOutputSchema,
  },
  async (input) => {
    const llmResponse = await chatPrompt(input);
    const output = llmResponse.output; // Corrected: property access
    if (!output) {
        throw new Error("No output from LLM for chatWithAgentOrGlobalFlow");
    }
    // The schema ensures aiResponse exists, but a direct check can be added for robustness if needed.
    // For example: if (typeof output.aiResponse !== 'string') throw new Error("Invalid AI response format");
    return { aiResponse: output.aiResponse };
  }
);

