
// import type { LLM_PROVIDERS } from '@/lib/constants'; // Not needed if LLMProvider is defined below

/**
 * @fileOverview Defines all shared TypeScript types and interfaces for the CodeAlchemist application.
 */

/**
 * Defines the available Large Language Model (LLM) providers.
 */
export const LLM_PROVIDERS_CONST = ["Groq", "Google Gemini", "OpenAI", "Anthropic", "LM Studio", "Ollama"] as const;
/**
 * Represents a specific LLM provider.
 * @typedef {typeof LLM_PROVIDERS_CONST[number]} LLMProvider
 */
export type LLMProvider = typeof LLM_PROVIDERS_CONST[number];


/**
 * Interface for LLM configuration settings.
 */
export interface LLMSettings {
  /** The selected LLM provider. */
  provider: LLMProvider;
  /** The API endpoint URL for the LLM provider. */
  apiUrl: string;
  /** The API key for the LLM provider. */
  apiKey: string;
  /** The specific model to be used from the provider. */
  model: string;
}

/**
 * Interface for Git configuration settings.
 */
export interface GitSettings {
  /** The URL of the Git repository. */
  repoUrl: string;
  /** The username for Git commits. */
  username: string;
  /** The email for Git commits. */
  email: string;
  /** The Personal Access Token (PAT) for Git authentication. */
  pat: string;
}

/**
 * Interface for overall application settings.
 */
export interface AppSettings {
  /** Global LLM configuration. */
  llmConfig: LLMSettings;
  /** Global Git configuration. */
  gitConfig: GitSettings;
  /** Flag to enable or disable debug mode. */
  debugMode: boolean;
}

/**
 * Interface defining capabilities for an AI agent.
 */
export interface AgentCapabilities {
  /** Whether the agent can access CodeAlchemist's own source code. */
  accessOwnCode: boolean;
  /** Whether the agent can execute commands or scripts (potentially dangerous). */
  execution: boolean;
  /** Whether the agent can interact with or manage virtual environments. */
  virtualEnv: boolean;
  /** Whether the agent can read and write files on the system (potentially dangerous). */
  readWrite: boolean;
}

/**
 * Interface for an AI agent's LLM configuration.
 */
export interface AgentLLMConfiguration {
  /** Whether the agent should use the global LLM settings. */
  useGlobal: boolean;
  /** Custom LLM settings if not using global. */
  customConfig?: Partial<LLMSettings>;
}

/**
 * Interface representing an AI agent.
 */
export interface Agent {
  /** Unique identifier for the agent. */
  id: string;
  /** Name of the agent. */
  name: string;
  /** Description of the agent's purpose and specialization. */
  description: string;
  /** The base system prompt that defines the agent's role and behavior. */
  systemPrompt: string;
  /** Capabilities granted to the agent. */
  capabilities: AgentCapabilities;
  /** LLM configuration for the agent. */
  llmConfig: AgentLLMConfiguration;
  /** Whether this is a default agent created by the system. */
  isDefault?: boolean;
  /** Whether this agent can be deleted by the user. */
  isDeletable?: boolean;
  /** Whether the name of this agent can be edited by the user. */
  isNameEditable?: boolean;
}

/**
 * Interface representing an AI agent group.
 */
export interface AIAgentGroup {
  /** Unique identifier for the group. */
  id: string;
  /** Name of the group. */
  name: string;
  /** Description of the group's purpose. */
  description: string;
  /** The main task or objective for the group, used as input for the orchestrator. */
  mainTask: string;
  /** Array of agent IDs participating in this group (OrquestadorFlujoAgentes is implicit). */
  agentIds: string[];
  /** Whether this is a default group created by the system. */
  isDefault?: boolean;
}

/**
 * Interface for a saved code snapshot.
 */
export interface CodeSnapshot {
  /** Unique identifier for the snapshot. */
  id: string;
  /** Descriptive name for the snapshot. */
  name: string;
  /** The code content of the snapshot. */
  code: string;
  /** ISO date string of when the snapshot was created. */
  createdAt: string;
  /** Source of the snapshot (e.g., original code, AI suggested code). */
  source?: 'original' | 'suggested' | 'codealchemist-current';
}

/**
 * Interface representing a file generated by an AI process.
 */
export interface GeneratedFile {
  /** Relative path of the file or folder. Folders should end with a '/'. */
  path: string;
  /** Content of the file. Empty for folders. */
  content: string;
  /** Optional flag to explicitly indicate if this is a folder. */
  isFolder?: boolean;
}

/**
 * Input type for the project generation flow.
 */
export interface GenerateProjectInput {
  /** Detailed description of the project to generate. */
  description: string;
  /** Optional system prompt of an agent, if generation is agent-driven. */
  agentSystemPrompt?: string;
}

/**
 * Result type for the project generation flow.
 */
export interface ProjectGenerationResult {
  /** A suggested name for the project. */
  projectName: string;
  /** Notes from the AI about the generated structure or next steps. */
  aiNotes: string;
  /** An array of generated files and folders. */
  files: GeneratedFile[];
  /** Optional log from group execution if generation was group-coordinated. */
  groupLog?: string;
}


/**
 * Represents a refactoring suggestion from an AI analysis.
 */
export interface RefactorSuggestion {
  /** The specific file, component, or area affected by the suggestion. */
  area: string;
  /** A detailed explanation of the proposed improvement. */
  description: string;
  /** Priority of the suggestion (High, Medium, or Low). */
  priority: "Alta" | "Media" | "Baja";
  /** Optional code snippets showing original and modified code. */
  snippetSuggested?: {
    original?: string;
    modified?: string;
  };
  /** Unique identifier for the suggestion (for UI key and tracking). */
  id: string;
  /** Current status of the suggestion in the UI. */
  status?: 'pending' | 'applied' | 'discarded';
}

/**
 * Input type for the code snippet analysis flow.
 */
export interface AnalyzeCodeSnippetInput {
  /** The code snippet to analyze. */
  code: string;
  /** Optional user instructions to focus the analysis. */
  userPrompt?: string;
  /** Optional hint for the programming language of the snippet. */
  language?: string;
  /** Optional system prompt of an agent if analysis is agent-driven. */
  agentSystemPrompt?: string;
}

/**
 * Output type for the code snippet analysis flow.
 */
export interface AnalyzeCodeSnippetOutput {
  /** An explanation of what the original code does. */
  explanation: string;
  /** The original code snippet that was analyzed. */
  originalCode: string;
  /** The suggested version of the code with improvements or alternatives. */
  suggestedCode: string;
}

/**
 * Represents a suggestion generated by the AutoUpdate feature.
 */
export interface AutoUpdateSuggestion {
  /** Unique identifier for the suggestion (for UI key). */
  id: string;
  /** The file path or area affected by the suggestion. */
  area: string;
  /** Description of the suggested improvement or correction. */
  suggestion: string;
  /** Priority of the suggestion. */
  priority: "Alta" | "Media" | "Baja";
  /** The complete suggested content of the file, if applicable. */
  fullFileContentSuggested?: string;
  /** An AI-generated prompt that could be used to implement this specific suggestion. */
  suggestedPromptForImplementation?: string;
  /** Current status of the suggestion in the UI (e.g., pending, applied). */
  status?: 'pending' | 'applied' | 'discarded';
  /** Flag to indicate if the suggestion content is being edited by the user. */
  isEditing?: boolean;
  /** The content of the suggestion as edited by the user. */
  userEditedContent?: string;
}

/**
 * Represents a message in a chat conversation.
 */
export interface ChatMessage {
  /** Unique identifier for the message. */
  id: string;
  /** Role of the entity that sent the message (user, AI assistant, or system). */
  role: 'user' | 'assistant' | 'system';
  /** Content of the message. */
  content: string;
  /** ISO date string of when the message was sent. */
  timestamp: string;
}

/**
 * Represents the selected source for LLM configuration.
 */
export interface LLMConfigSourceOption {
  /** Type of the LLM configuration source. */
  type: 'Ajustes Globales' | 'Agente' | 'Grupo';
  /** Identifier for the agent or group, if applicable. */
  id?: string;
  /** Name of the agent or group for display purposes, if applicable. */
  name?: string;
}

/**
 * Data structure for the agent creation/editing form.
 * Omits system-managed properties from the base Agent type and makes 'id' optional.
 */
export type AgentFormData = Omit<Agent, 'id' | 'isDefault' | 'isDeletable' | 'isNameEditable'> & { id?: string };
/**
 * Data structure for the AI agent group creation/editing form.
 * Omits system-managed properties from the base AIAgentGroup type and makes 'id' optional.
 */
export type GroupFormData = Omit<AIAgentGroup, 'id' | 'isDefault'> & { id?: string };

/**
 * Input type for the AI-assisted agent definition suggestion flow.
 */
export interface SuggestAgentDefinitionInput {
  /** A detailed description of the role and responsibilities for the agent to be created. */
  roleDescription: string;
}
/**
 * Output type for the AI-assisted agent definition suggestion flow.
 * Provides core properties for an agent; LLM configuration is typically set by the user or defaults.
 */
export type SuggestAgentDefinitionOutput = Omit<AgentFormData, 'llmConfig' | 'id'> & {
  /** Suggested capabilities for the agent, based on its role. */
  capabilities: AgentCapabilities;
};

/**
 * Information about an existing agent, used when suggesting participants for a new group.
 */
export interface AgentInfoForGroupSuggestion {
    /** Unique identifier of the agent. */
    id: string;
    /** Name of the agent. */
    name: string;
    /** Description of the agent. */
    description: string;
}
/**
 * Input type for the AI-assisted group definition suggestion flow.
 */
export interface SuggestGroupDefinitionInput {
  /** A detailed description of the task or objective the AI agent group should achieve. */
  groupTaskDescription: string;
  /** A list of existing AI agents available for inclusion in the group. */
  availableAgents: AgentInfoForGroupSuggestion[];
}
/**
 * Output type for the AI-assisted group definition suggestion flow.
 */
export type SuggestGroupDefinitionOutput = Omit<GroupFormData, 'id'>;


/**
 * Input type for the "Refactor Project with AI" flow.
 */
export interface RefactorProjectWithAIInput {
  /** The project source, as a reference (e.g., "uploaded_file:myproject.zip" or Git URL). */
  projectSource: string;
  /** Specific goals for the refactoring process. */
  goals?: string;
  /** General priority guiding the refactoring (e.g., Security, Readability). */
  priority?: string;
  /** Suggested depth for the analysis (e.g., number of levels). */
  searchDepth?: number;
  /** Specific functional area or quality attribute to focus on. */
  focusArea?: string;
}

/**
 * Output type for the "Refactor Project with AI" flow.
 */
export interface RefactorProjectWithAIOutput {
  /** An array of refactoring suggestions. */
  suggestions: Array<{
    area: string;
    description: string;
    priority: 'Alta' | 'Media' | 'Baja';
    snippetSuggested?: {
      original?: string;
      modified?: string;
    };
  }>;
  /** Optional log from group execution if refactoring was group-coordinated. */
  groupLog?: string;
}

/**
 * Input type for analyzing project code (used for AutoUpdate and generic project analysis).
 */
export interface AnalyzeCodeInput {
  /** Indicates if analyzing local code, a Git repo, or direct string content. */
  sourceCodeLocation: 'Local' | 'Git' | 'UploadedString';
  /** The actual project content (e.g., for 'UploadedString' or fetched Git content). */
  projectContent?: string;
  /** The URL of the Git repository if sourceCodeLocation is Git. */
  gitRepoUrl?: string;
  /** Deprecated, use focusArea. Specific areas or concerns to focus the analysis on. */
  analysisPreferences?: string;
  /** Suggested depth for the analysis (e.g., number of levels). */
  searchDepth?: number;
  /** Specific functional area, module, or quality attribute to concentrate the analysis on. */
  focusArea?: string;
}

/**
 * Output type for project code analysis.
 */
export interface AnalyzeCodeOutput {
  /** A concise title summarizing the findings of the analysis. */
  analysisTitle: string;
  /** A list of components, modules, or files identified as areas of concern or interest. */
  identifiedAreas: string[];
  /** A list of detailed suggestions for improvement. */
  detailedSuggestions: Array<{
    area: string;
    suggestion: string;
    priority: 'Alta' | 'Media' | 'Baja';
    suggestedContent?: string;
    suggestedPromptForImplementation?: string;
  }>;
  /** An overall assessment of the code quality and potential issues. */
  generalAssessment: string;
  /** Optional log from group execution if analysis was group-coordinated. */
  groupLog?: string;
  /** Optional list of high-level ideas for general project improvement. */
  overallImprovementIdeas?: string[];
}

/**
 * Represents a generic note object.
 */
export interface NoteType {
  /** Unique identifier for the note. */
  id: string;
  /** Content of the note. */
  content: string;
  /** Optional ISO date string of when the note was created. */
  createdAt?: string;
}
